version: '3.9'
services:
  db:
    image: mariadb:10.4
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_DATABASE: invest-db
      MYSQL_ROOT_PASSWORD: rsdntvl
      MYSQL_USER: docker
      MYSQL_PASSWORD: rsdntvl
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - 6001:3306
    expose:
      - 6001
    networks:
      - invest-network
  # invest:
  #   image: niltonfq/invest
  #   restart: always
  #   build: ./invest
  #   working_dir: /invest
  #   environment:
  #     TZ: America/Sao_Paulo
  #     SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/invest-db?useTimezone=true&serverTimezone=UTC
  #     SPRING.DATASOURCE.USERNAME: root
  #     SPRING.DATASOURCE.PASSWORD: rsdntvl
  #   ports:
  #     - 81:81
  #   command: mvn spring-boot:run
  #   depends_on:
  #     - db
  #   networks:
  #     - invest-network
networks:
  invest-network:
    driver: bridge
