version: '3.9'
services:
  db:
    image: mariadb:10.4
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_DATABASE: auth-db
      MYSQL_ROOT_PASSWORD: rsdntvl
      MYSQL_USER: docker
      MYSQL_PASSWORD: rsdntvl
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - 6000:3306
    expose:
      - 6000
    networks:
      - auth-network
  # auth:
  #   image: niltonfq/auth
  #   restart: always
  #   build: ./auth
  #   working_dir: /auth
  #   environment:
  #     TZ: America/Sao_Paulo
  #     SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/auth-db?useTimezone=true&serverTimezone=UTC
  #     SPRING.DATASOURCE.USERNAME: root
  #     SPRING.DATASOURCE.PASSWORD: rsdntvl
  #   ports:
  #     - 80:80
  #   command: mvn spring-boot:run
  #   depends_on:
  #     - db
  #   networks:
  #     - auth-network
networks:
  auth-network:
    driver: bridge
