name: invest
description: A new Flutter package project.
version: 1.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  micro_core:
    path: ../micro_core
  excel: ^2.0.1
  file_picker: ^5.2.5
  
  commons_design_system:
    path: ../commons_design_system
      
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true